#!/usr/bin/env python3
"""
Generate js/offers-italia-data.js from italia.csv (MonzaFlora offers).

Pure local, NO network access. Run:  python tools/generate-offers-italia-data.py

CSV columns (verbatim header):
    Posizione, Ragione sociale, Email, Comune, Provincia, Source

Each generated record keeps the Italian values untouched:
    t  = Posizione (job position)
    e  = Ragione sociale (employer name)
    m  = Email
    cm = Comune
    pv = Provincia
    u  = Source URL (the original job offer link)
    a  = Arabic helper translation of t (added locally; "-" when none)
Missing CSV values stay as-is ("-"), the JS layer renders them as مكتقدرش نعرفو.
Exception: when Posizione (t) is empty, the title is derived from the Source
slug (fallback, see slug_title) — an existing Posizione is never replaced.
The Arabic line (see ar_title / AR_TITLES) is hand-authored, natural Arabic
for the profession; it never replaces or alters the Italian title, and legal
references in complex titles are kept verbatim. No network is ever used.
"""

import csv
import io
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CSV_PATH = os.path.join(ROOT, "italia.csv")
OUT_PATH = os.path.join(ROOT, "js", "offers-italia-data.js")

COLUMNS = ["Posizione", "Ragione sociale", "Email", "Comune", "Provincia", "Source"]
KEYS = ["t", "e", "m", "cm", "pv", "u"]


def slug_title(url):
    """Readable Italian title derived from the Source slug — local and deterministic.

    Only used as a FALLBACK when Posizione is empty; an existing Posizione is
    never replaced. Steps: strip fragment/query -> last part after /offerte/
    -> '-' becomes spaces -> drop a trailing slug index ("-6", "-61") only when
    the segment before it is NOT numeric (so "...-dlgs-154-2016" is preserved)
    -> sentence case. No network, no scraping.
    """
    clean = url.split("#", 1)[0].split("?", 1)[0]
    tail = clean.split("/offerte/")[-1] if "/offerte/" in clean else clean.rstrip("/").split("/")[-1]
    parts = [p for p in tail.split("-") if p]
    if len(parts) >= 2 and parts[-1].isdigit() and not parts[-2].isdigit():
        parts.pop()
    title = " ".join(parts).strip()
    if title:
        title = title[0].upper() + title[1:]
    return title


# ---------------------------------------------------------------------------
# Arabic translations of the Italian job titles (a). Hand-authored, natural,
# professional Arabic for the profession — never a literal word-for-word when
# that would read badly. The Italian title stays the primary reference (t) and
# is never modified; the Arabic only helps the Arabic-speaking user understand
# the job. Legal references in complex titles (e.g. "dlgs 154 2016") are kept
# verbatim. Keys are the normalized (lowercase, collapsed-spaces) title.
# ---------------------------------------------------------------------------
AR_TITLES = {
    "giardiniere": "بستاني / عامل حدائق",
    "giardiniere giardiniera": "بستاني / عاملة حدائق",
    "giardiniere giardiniera qualificato": "بستاني / عاملة حدائق مؤهلة",
    "giardiniere con esperienza": "بستاني بخبرة",
    "giardiniere con esperienza anche con uso": "بستاني بخبرة",
    "giardiniere specializzato": "بستاني متخصص",
    "giardiniere specializzato e o qualificato": "بستاني متخصص أو مؤهل",
    "giardiniere specializzato e qualificato": "بستاني متخصص ومؤهل",
    "giardiniere specializzato caposquadra": "بستاني متخصص رئيس فريق",
    "giardiniere qualificato": "بستاني مؤهل",
    "giardiniere qualificato con esperienza": "بستاني مؤهل بخبرة",
    "giardiniere qualificato con esperienza verde": "بستاني مؤهل بخبرة في المساحات الخضراء",
    "giardiniere qualificato e giardiniere comune": "بستاني مؤهل وبستاني عادي",
    "giardiniere qualificato con esperienza giardino": "بستاني مؤهل بخبرة في الحدائق",
    "giardiniere esperto": "بستاني خبير",
    "giardiniere esperto disposto a lavorare anche": "بستاني خبير مستعد للعمل أيضاً",
    "giardiniere esperto potature e uso trattori": "بستاني خبير في التقليم واستعمال الجرارات",
    "giardiniere esperto con partita iva": "بستاني خبير بنظام العمل الحر",
    "giardiniere base": "بستاني مبتدئ",
    "giardiniere base con qualifica": "بستاني مبتدئ مؤهل",
    "giardiniere con partita iva": "بستاني بنظام العمل الحر (P.IVA)",
    "giardiniere con p iva": "بستاني بنظام العمل الحر (P.IVA)",
    "giardiniere con patente c": "بستاني بالرخصة C",
    "giardiniere con patente guida per furgone": "بستاني برخصة قيادة شاحنة صغيرة",
    "giardiniere con esperienza potature": "بستاني بخبرة في التقليم",
    "giardiniere con esperienza e corsi": "بستاني بخبرة ودورات تكوينية",
    "giardiniere con formazione o esperienza": "بستاني بتكوين أو خبرة",
    "giardiniere con interesse e esperienza anche": "بستاني برغبة وخبرة",
    "giardiniere con minimo 2 anni di esperienza": "بستاني بخبرة سنتين على الأقل",
    "giardiniere con esperienza di potatura di": "بستاني بخبرة في التقليم",
    "giardiniere senza esperienza": "بستاني بدون خبرة",
    "giardiniere minima esperienza": "بستاني بخبرة دنيا",
    "giardiniere anche prima esperienza": "بستاني يقبل أول خبرة",
    "giardiniere gia formato": "بستاني مكوّن",
    "giardiniere diplomato": "بستاني حاصل على شهادة",
    "giardiniere comune": "بستاني عادي",
    "giardiniere completo": "بستاني متكامل",
    "giardiniere autonomo": "بستاني مستقل",
    "giardiniere apprendista": "بستاني متدرب",
    "giardiniere apprendista e qualificato": "بستاني متدرب ومؤهل",
    "giardiniere professionista": "بستاني محترف",
    "giardiniere professionista a piva": "بستاني محترف بنظام العمل الحر",
    "giardiniere professionale manutentore": "بستاني محترف في الصيانة",
    "giardiniere manutentore": "بستاني صيانة",
    "giardiniere manutentore del verde": "بستاني صيانة المساحات الخضراء",
    "giardiniere manutentore con esperienza": "بستاني صيانة بخبرة",
    "giardiniere manutenzione del verde": "بستاني صيانة المساحات الخضراء",
    "giardiniere manutentore verde esterno ed": "بستاني صيانة المساحات الخارجية",
    "giardiniere caposquadra": "بستاني رئيس فريق",
    "giardiniere capo squadra": "بستاني رئيس فريق",
    "giardiniere giardiniere caposquadra": "بستاني رئيس فريق",
    "giardiniere vivaista": "بستاني عامل في المشاتل النباتية",
    "giardiniere vivaista manutentore del verde": "بستاني مشاتل وصيانة المساحات الخضراء",
    "giardiniere florovivaista": "بستاني ومتخصص في زراعة النباتات",
    "giardiniere paesaggista": "بستاني متخصص في تنسيق الحدائق",
    "giardiniere tecnico del verde": "بستاني فني للمساحات الخضراء",
    "giardiniere tecnico impianti irrigazione": "بستاني فني أنظمة الري",
    "giardiniere arboricoltore": "بستاني مختص في العناية بالأشجار",
    "giardiniere agricoltore": "بستاني مزارع",
    "giardiniere agricoltore operatore forestale": "بستاني مزارع وعامل غابات",
    "giardiniere custode": "بستاني حارس",
    "giardiniere custode casa privata": "بستاني حارس منزل خاص",
    "giardiniere potatore": "بستاني مختص في التقليم",
    "giardiniere potatore con patentino ple": "بستاني تقليم برخصة PLE",
    "giardiniere e climber": "بستاني ومتخصص في العمل المرتفع بالأشجار",
    "giardiniere tree climber": "بستاني متخصص في العمل المرتفع بالأشجار",
    "giardiniere treeclimber": "بستاني متخصص في العمل المرتفع بالأشجار",
    "giardiniere treeclimbing": "بستاني متخصص في العمل المرتفع بالأشجار",
    "giardiniere alta quota": "بستاني للأماكن المرتفعة",
    "giardiniere tuttofare": "بستاني متعدد المهام",
    "giardiniere allestitore stand": "بستاني مجهّز منصّات العرض",
    "giardiniere operatore macchinari": "بستاني مشغّل آليات",
    "giardiniere uso piccole attrezzature": "بستاني يستعمل معدات صغيرة",
    "giardiniere e autista patente c": "بستاني وسائق بالرخصة C",
    "giardiniere e ortolano per orto produttivo": "بستاني ومزارع خضروات إنتاجية",
    "giardiniere e o arboricoltore": "بستاني أو مختص في الأشجار",
    "giardiniere o operaio agricolo": "بستاني أو عامل فلاحي",
    "giardiniere artigiano": "بستاني حرفي",
    "giardiniere creazione e manutenzione aree": "بستاني إنشاء وصيانة المساحات",
    "giardiniere per parco botanico storico": "بستاني لحديقة نباتية تاريخية",
    "giardiniere a bergamo": "بستاني في برغامو",
    "giardiniere a con esperienza": "بستاني بخبرة",
    "giardiniere con formazione da formare": "بستاني يتكوّن أثناء العمل",
    "giardiniere con esperienza o da formare": "بستاني بخبرة أو يتكوّن أثناء العمل",
    "giardiniere preferibilmente esperto": "بستاني يُفضّل أن يكون خبيراً",
    "giardiniere edile stradale": "بستاني وعامل أبنية وطرق",
    "giardiniere con esperienza anche demolitore": "بستاني بخبرة في أعمال الهدم",
    "giardiniere di consolidato esperienza": "بستاني بخبرة راسخة",
    "giardiniere di manutenzione": "بستاني صيانة",
    "giardiniere forestale": "بستاني غابات",
    "giardiniere giardiniere": "بستاني",
    "giardiniere manutentore verde": "بستاني صيانة المساحات الخضراء",
    "giardiniere manutentore a verde": "بستاني صيانة المساحات الخضراء",
    "giardiniere manutentore verde privato": "بستاني صيانة المساحات الخضراء الخاصة",
    "giardiniere per manutenzione aree verdi": "بستاني لصيانة المساحات الخضراء",
    "giardiniere praticante": "بستاني متدرّب",
    "giardiniere part time": "بستاني بدوام جزئي",
    "giardiniere a partita iva": "بستاني بنظام العمل الحر",
    "giardiniere semplice": "بستاني",
    "giardiniere specializzato potatore": "بستاني متخصص في التقليم",
    "giardiniere con patentino ple": "بستاني برخصة PLE",
    "giardiniere e manutentore del verde": "بستاني وعامل صيانة المساحات الخضراء",
    "giardiniere e manutentore": "بستاني وعامل صيانة",
    "giardiniere esperto manutentore": "بستاني خبير في الصيانة",
    "giardiniere coordinatore": "بستاني منسّق",
    "giardiniere con esperienza di potatura": "بستاني بخبرة في التقليم",
    "giardiniere con attestato fitosanitario": "بستاني بشهادة المعالجة النباتية",
    "giardiniere manutentore e potatore": "بستاني صيانة وتقليم",
    "giardiniere addetto alle vendite": "بستاني موظف مبيعات",
    "giardiniere addetto alle vandite": "بستاني موظف مبيعات",
    "giardiniere addetto al garden": "بستاني موظف في متجر الحدائق",
    "giardiniere addetto al vivaio": "بستاني موظف في المشتل النباتي",
    "giardiniere capo area": "بستاني مسؤول منطقة",
    "giardiniere e potatore": "بستاني ومختص في التقليم",
    "giardiniere potatore con esperienza": "بستاني تقليم بخبرة",
    "giardiniere apprendista qualificato": "بستاني متدرّب مؤهل",
    "giardiniere junior": "بستاني مبتدئ",
    "giardiniere operaio": "بستاني عامل",
    "giardiniere coordinator del verde": "بستاني منسّق المساحات الخضراء",
    "giardiniere tecnico": "بستاني فني",
    "giardiniere agronomo": "بستاني مهندس زراعي",
    "giardiniere venditore": "بستاني بائع",
    "giardiniere autista": "بستاني سائق",
    "giardiniere e autista": "بستاني وسائق",
    "giardiniere scapestratore": "بستاني عامل رفع",
    "giardiniere arboricoltore certificato": "بستاني مختص معتمد في العناية بالأشجار",
    "giardiniere paesaggista manutentore": "بستاني تنسيق حدائق وصيانة",
    "giardiniere full time": "بستاني بدوام كامل",
    "giardiniere con esperienza di lavoro": "بستاني بخبرة عمل",
    "giardiniere formarsi": "بستاني يتكوّن أثناء العمل",
    "giardiniere motivato": "بستاني متحفز",
    "giardiniere con esperienza nella potatura": "بستاني بخبرة في التقليم",
    "giardiniere molto esperto": "بستاني ذو خبرة كبيرة",
    "giardiniere anziano esperto": "بستاني كبير وخبير",
    "giardiniere autonomo con partita iva": "بستاني مستقل بنظام العمل الحر",
    "giardiniere esperto con attrezzature": "بستاني خبير ومتوفر على معداته",
    "giardiniere con esperienza e auto": "بستاني بخبرة ومتوفر على سيارة",
    "giardiniere con esperienza anche nel taglio": "بستاني بخبرة في القص أيضاً",
    "giardiniere professionista capo squadra": "بستاني محترف رئيس فريق",
    "giardiniere esperto di potature": "بستاني خبير في التقليم",
    "giardiniere con esperienza senso": "بستاني بخبرة في تسلق الأشجار",
    "giardiniere capitano squadra": "بستاني قائد فريق",
    "capo giardiniere": "رئيس البستانيين",
    "capogiardiniere": "رئيس البستانيين",
    "capo squadra giardiniere": "رئيس فريق بستانيين",
    "capo squadra manutentore aree verdi": "رئيس فريق صيانة المساحات الخضراء",
    "capo squadra manutentore del verde": "رئيس فريق صيانة المساحات الخضراء",
    "caposquadra giardiniere": "رئيس فريق بستانيين",
    "caposquadra manutentore del verde": "رئيس فريق صيانة المساحات الخضراء",
    "caposquadra": "رئيس فريق",
    "caposquadra responsabile cantieri": "رئيس فريق مسؤول عن الورشات",
    "caposquadra agricolo": "رئيس فريق فلاحي",
    "caposquadra settore agricoltura": "رئيس فريق قطاع الفلاحة",
    "caposquadra agricoltura sociale": "رئيس فريق الفلاحة الاجتماعية",
    "capo squadra agricoltura": "رئيس فريق فلاحة",
    "capo squadra orto sociale": "رئيس فريق الحديقة الاجتماعية",
    "capo area manutenzione verde": "مسؤول منطقة صيانة المساحات الخضراء",
    "capocantiere giardiniere professionista": "رئيس ورشة بستاني محترف",
    "capo squadra": "رئيس فريق",
    "capo cantiere": "رئيس ورشة",
    "capoosquadra giardiniere": "رئيس فريق بستانيين",
    "capo squadra giardiniere paesaggista": "رئيس فريق بستاني تنسيق حدائق",
    "caposquadra del verde": "رئيس فريق المساحات الخضراء",
    "caposquadra cantieri": "رئيس فريق الورشات",
    "caposquadra settore verde": "رئيس فريق قطاع المساحات الخضراء",
    "caposquadra manutenzione aree verdi": "رئيس فريق صيانة المساحات الخضراء",
    "responsabile settore verde": "مسؤول قطاع المساحات الخضراء",
    "responsabile settore ambiente": "مسؤول قطاع البيئة",
    "responsabile settore garden": "مسؤول قطاع متجر الحدائق",
    "responsabile reparto garden": "مسؤول قسم متجر الحدائق",
    "responsabile": "مسؤول",
    "responsabile di commessa": "مسؤول المشروع",
    "responsabile operativo": "مسؤول تنفيذي",
    "responsabile commerciale": "مسؤول تجاري",
    "responsabile impianti d irrigazione": "مسؤول أنظمة الري",
    "responsabile officina settore del verde": "مسؤول ورشة قطاع المساحات الخضراء",
    "responsabile dei giardini realta storica": "مسؤول حدائق موقع تاريخي",
    "responsabile di negozio piante": "مسؤول متجر نباتات",
    "responsabile all approvvigionamento": "مسؤول التموين",
    "responsabile per squadre di giardinieri": "مسؤول عن فرق البستانيين",
    "responsabile produzione ortofrutticola biologica": "مسؤول إنتاج الخضروات والفواكه البيولوجية",
    "responsabile tecnico": "مسؤول تقني",
    "responsabile manutenzioni": "مسؤول الصيانة",
    "responsabile gestione commessa": "مسؤول إدارة المشروع",
    "responsabile area commerciale": "مسؤول المنطقة التجارية",
    "responsabile preventivazione": "مسؤول إعداد التكاليف",
    "coordinatore servizio manutenzione aree verdi": "منسق خدمة صيانة المساحات الخضراء",
    "coordinatore servizi manutenzione del verde": "منسق خدمات صيانة المساحات الخضراء",
    "coordinatore tecnico manutenzione verde pubblico": "منسق فني صيانة المساحات الخضراء العمومية",
    "coordinatore settore verde": "منسق قطاع المساحات الخضراء",
    "coordinatore di agenzia negozio": "منسق وكالة ومتجر",
    "coordinatore di negozio": "منسق المتجر",
    "direttore tecnico": "مدير تقني",
    "dirigente": "مدير تنفيذي",
    "imprenditore": "صاحب مشروع",
    "titolo di lavoro": "صاحب عمل",
    "titolare": "صاحب العمل",
    "titolare impresa giardinaggio": "صاحب شركة أعمال حدائق",
    "titolare ditta di giardinaggio": "صاحب شركة أعمال حدائق",
    "titolare progetto verde": "صاحب مشروع المساحات الخضراء",
    "titolare partita iva individuale": "صاحب عمل حر بتشخيص فردي",
    "titolare impresa": "صاحب شركة",
    "legale rappresentante": "الممثل القانوني",
    "presidente": "رئيس المؤسسة",
    "socio azienda": "شريك المؤسسة",
    "socia cooperatrice": "شريكة في تعاونية",
    "socia coadiuvante": "شريكة مساعدة",
    "collaboratore": "متعاون / مساعد",
    "collaboratrice": "متعاونة / مساعدة",
    "collaboratore con p iva": "متعاون بنظام العمل الحر (P.IVA)",
    "collaboratore a partita iva": "متعاون بنظام العمل الحر",
    "collaboratore a progetto": "متعاون على أساس مشروع",
    "collaboratore full time per progettazione": "متعاون بدوام كامل للتصميم",
    "collaboratore giardiniere": "متعاون بستاني",
    "collaboratore gestione stalle": "متعاون في تدبير الإسطبلات",
    "collaboratori in attivita di giardinaggio": "متعاونون في أعمال الحدائق",
    "collaboratore esperto": "متعاون خبير",
    "collaboratore alla progettazione": "متعاون في التصميم",
    "collaboratore amministrativo": "متعاون إداري",
    "collaboratore in vivaio": "متعاون في المشتل النباتي",
    "dipendente": "موظف",
    "dipendente stagionale": "موظف موسمي",
    "consulente": "مستشار",
    "consulente del lavoro": "مستشار الشغل",
    "consulente di vendita": "مستشار مبيعات",
    "agente di commercio": "وكيل تجاري",
    "libero professionista": "عامل حر",
    "artigiano": "حرفي",
    "artigiano giardiniere": "حرفي بستاني",
    "artigiano con p i": "حرفي بنظام العمل الحر",
    "artigiano con partita iva": "حرفي بنظام العمل الحر",
    "artigiano del verde": "حرفي المساحات الخضراء",
    "aspirante fiorista artigiano del verde": "بائعة زهور مبتدئة حرفية المساحات الخضراء",
    "apprendista": "متدرب",
    "apprendista giardiniere": "متدرب بستاني",
    "apprendista giardiniere e giardiniere": "متدرب بستاني وبستاني",
    "apprendista giardiniere giardiniere": "متدرب بستاني وبستاني",
    "apprendista aspirante giardiniere": "متدرب بستاني مبتدئ",
    "apprendista operaio": "عامل متدرب",
    "stagista": "متدرب",
    "stagista apprendista": "متدرب",
    "tirocinante stagista": "متدرب",
    "tirocinante stagista dal 20 aprile al": "متدرب ابتداءً من 20 أبريل",
    "tirocinante operaio": "عامل متدرب",
    "tirocinio giardiniere installatore del verde": "تدريب بستاني مُركب المساحات الخضراء",
    "tirocinio manutenzione del verde": "تدريب في صيانة المساحات الخضراء",
    "tirocinante": "متدرب",
    "stage giardiniere manutentore del verde": "تدريب بستاني صيانة المساحات الخضراء",
    "stage direzione lavori": "تدريب في إدارة الأشغال",
    "stage giardiniere": "تدريب بستاني",
    "stage manutenzione verde": "تدريب صيانة المساحات الخضراء",
    "neodiplomato": "خريج حديث",
    "perito agrario neodiplomato": "خريج حديث في العلوم الفلاحية",
    "operaio": "عامل",
    "operaia": "عاملة",
    "operaio giardiniere": "عامل بستاني",
    "operaio giardinere": "عامل بستاني",
    "operaio giardiniere con esperienza": "عامل بستاني بخبرة",
    "operaio giardiniere e fiorista": "عامل بستاني وبائع زهور",
    "operaio giardiniere e apprendista": "عامل بستاني ومتدرب",
    "operaio aiuto giardiniere": "عامل مساعد بستاني",
    "operaio agricolo": "عامل فلاحي",
    "operaia agricola": "عاملة فلاحية",
    "operaio agricolo con esperienza utilizzo": "عامل فلاحي بخبرة في استعمال الآليات",
    "operaio specializzato": "عامل متخصص",
    "operaio specializzato qualificato": "عامل متخصص مؤهل",
    "operaio specializzato manutenzione aree verdi": "عامل متخصص في صيانة المساحات الخضراء",
    "operaio specializzato manutenzione del verde": "عامل متخصص في صيانة المساحات الخضراء",
    "operaio specializzato manutenzione del": "عامل متخصص في صيانة المساحات الخضراء",
    "operaio qualificato": "عامل مؤهل",
    "operaio comune": "عامل عادي",
    "operaio comune stagionale": "عامل عادي موسمي",
    "operaio generico": "عامل عام",
    "operaio generico per inserimento organico": "عامل عام للإدماج في الفريق",
    "operaio manutenzione verde": "عامل صيانة المساحات الخضراء",
    "operaio manutenzione verde e civile": "عامل صيانة المساحات الخضراء والمدنية",
    "operaio manutentore": "عامل صيانة",
    "operaio del verde giardiniere": "عامل المساحات الخضراء بستاني",
    "operaio del verde": "عامل في المساحات الخضراء",
    "operaio vivaista addetto alle vendite": "عامل مشاتل موظف مبيعات",
    "operaio florovivaista": "عامل متخصص في زراعة النباتات",
    "operaio part time": "عامل بدوام جزئي",
    "operaio part time full time": "عامل بدوام جزئي أو كامل",
    "operaio tempo determinato giardiniere": "عامل بعقد محدد بستاني",
    "operaio stagionale addetto alla manutenzione": "عامل موسمي للصيانة",
    "operaio patente c": "عامل بالرخصة C",
    "operaio tecnico installatore": "عامل فني مُركب",
    "operaio tecnico pest control": "عامل فني مكافحة الآفات",
    "operaio per lavori di giardinaggio manutenzioni": "عامل أعمال حدائق وصيانة",
    "operaio per attivita di allontanamento volatili": "عامل أعمال إبعاد الطيور",
    "operaio per attivita di disinfestazione e": "عامل أعمال مكافحة الآفات",
    "operoario specializzato": "عامل متخصص",
    "operai e da impiegare in produzione e preparazione": "عمال للإنتاج والتحضير",
    "operatore del verde": "عامل في المساحات الخضراء",
    "operatore del verde giardiniere": "عامل المساحات الخضراء بستاني",
    "operatore agricolo": "عامل فلاحي",
    "operatore agricolo tirocinante": "عامل فلاحي متدرب",
    "operatore tecnico": "فني تشغيل",
    "operatore esperto": "عامل خبير",
    "operatore specializzato manutenzione del verde": "عامل متخصص في صيانة المساحات الخضراء",
    "operatore specializzato manutenzione del": "عامل متخصص في الصيانة",
    "operatore di campagna": "عامل ميداني",
    "operatore per progetto di agricoltura sociale": "عامل في مشروع الفلاحة الاجتماعية",
    "operatore agro ambientale": "عامل فلاحي بيئي",
    "operaio comune o qualificato": "عامل عادي أو مؤهل",
    "operatore forestale": "عامل غابات",
    "operatori forestali e o giardinieri": "عمال غابات أو بستانيون",
    "operatore macchine movimento terra": "عامل مشغّل آليات حفر",
    "operatore macchinari": "مشغّل آليات",
    "operatore esperto di motosega": "عامل خبير في المنشار الآلي",
    "operatore giardiniere": "عامل بستاني",
    "aiuto giardiniere": "مساعد بستاني",
    "aiuto giardiniere giardiniere con esperienza": "مساعد بستاني وبستاني بخبرة",
    "aiuto giardiniere con voglia di imparare": "مساعد بستاني برغبة في التعلم",
    "aiuto fiorista e giadiniere": "مساعد بائع زهور وبستاني",
    "aiutante": "مساعد",
    "aiuto ortolano": "مساعد مزارع خضروات",
    "aiuto stalla ovini e bovini in piccola stalla": "مساعد إسطبل للأغنام والأبقار في إسطبل صغير",
    "assistente tecnico del verde": "مساعد فني للمساحات الخضراء",
    "assistente tecnico di commessa": "مساعد فني المشروع",
    "assistente tecnico": "مساعد فني",
    "assistente di vivaio": "مساعد في المشتل النباتي",
    "assistente fiorista": "مساعد بائع زهور",
    "assistente direzione lavori": "مساعد إدارة الأشغال",
    "assistente agricolo nel settore della canapa": "مساعد فلاحي في قطاع القنب",
    "assistente alla coltivazione fuori suolo": "مساعد في الزراعة بدون تربة",
    "assietente alla coltivazione": "مساعد في الزراعة",
    "assistente di cantiere": "مساعد في الورشة",
    "assistente amministrativo": "مساعد إداري",
    "aiuto giardiniere con esperienza": "مساعد بستاني بخبرة",
    "addetto garden center": "موظف مركز بيع منتجات الحدائق",
    "addetto al garden": "موظف متجر الحدائق",
    "addetto ai garden": "موظف متاجر الحدائق",
    "addetto a garden": "موظف في متجر الحدائق",
    "addetto garden e vivaio": "موظف متجر الحدائق والمشاتل",
    "addetto garden center e vivaio": "موظف مركز بيع الحدائق والمشاتل",
    "addetto a reparto giardinaggio": "موظف قسم أعمال الحدائق",
    "addetto vendita": "موظف مبيعات",
    "addetto a vendite": "موظف مبيعات",
    "addetto vendita garden piante": "موظف مبيعات نباتات الحدائق",
    "addetto vendita piante": "موظف مبيعات نباتات",
    "addetti vendita piante e fiori": "موظفو مبيعات نباتات وزهور",
    "addetto a produzione florovivaistica": "موظف إنتاج نباتات",
    "addetto a invasatura": "موظف زرع النباتات في الأواني",
    "addetto manutenzione aree verdi": "موظف صيانة المساحات الخضراء",
    "addetto manutenzioni verde pubblico": "موظف صيانة المساحات الخضراء العمومية",
    "addetto manutenzione del verde": "موظف صيانة المساحات الخضراء",
    "addetto alla manutenzione delle aree verdi": "موظف صيانة المساحات الخضراء",
    "addetto a manutenzione giardini": "موظف صيانة حدائق",
    "addetto alla manutenzione del verde": "موظف صيانة المساحات الخضراء",
    "addetto giardinaggio emporio": "موظف أعمال حدائق في المحل",
    "addetto giardiniere addetta al garden center": "موظف بستاني في مركز بيع الحدائق",
    "addetto stalla e manutenzione verde aziendale": "موظف إسطبل وصيانة المساحات الخضراء",
    "addetto a ufficio tecnico pest control": "موظف مكتب فني مكافحة الآفات",
    "addetto vivaio": "موظف المشتل النباتي",
    "addetto al vivaio": "موظف المشتل النباتي",
    "adetto vivaio": "موظف المشتل النباتي",
    "addetto vivaio serra": "موظف مشتل وصوبة",
    "aaddetto al vivaio e serra fredda": "موظف مشتل وصوبة باردة",
    "addetto al vivaio e giardinaggio": "موظف مشتل وأعمال حدائق",
    "addetto alla soldatura": "موظف لحام",
    "addessa al garden": "موظفة متجر الحدائق",
    "addetta al garden": "موظفة متجر الحدائق",
    "addetta al garden center": "موظفة مركز بيع الحدائق",
    "addetta o vendita garden": "موظفة مبيعات متجر الحدائق",
    "addetta fioreria e piante interno": "موظفة قسم الزهور والنباتات الداخلية",
    "addetta o fioreria e serra calda": "موظفة زهور وصوبة دافئة",
    "addetta alle vendite fioreria": "موظفة مبيعات قسم الزهور",
    "addetto alle vendite fioreria": "موظف مبيعات قسم الزهور",
    "addetto alle vendite giardino e vivaio": "موظف مبيعات حدائق ومشاتل",
    "addetto vivilsta": "موظف مشتل نباتات",
    "addetto serra": "موظف الصوبة",
    "addetta serra": "موظفة الصوبة",
    "addetta vivaio": "موظفة المشتل النباتي",
    "addetto alla coltivazione": "موظف الزراعة",
    "addetta alla coltivazione": "موظفة الزراعة",
    "addetto piantumazione": "موظف غرس النباتات",
    "addetto a fioreria": "موظف قسم الزهور",
    "addetta a fioreria": "موظفة قسم الزهور",
    "manutentore del verde": "عامل صيانة المساحات الخضراء",
    "manutentore del verde dlgs 154 2016": "عامل صيانة المساحات الخضراء dlgs 154/2016",
    "manutentore del verde giardiniere": "عامل صيانة المساحات الخضراء بستاني",
    "manutentore del verde potatore guida trattori": "عامل صيانة مساحات خضراء سائق جرار",
    "manutentore del verde e servizio manutenzioni": "عامل صيانة المساحات الخضراء وخدمات صيانة",
    "manutentore aree verdi": "عامل صيانة المساحات الخضراء",
    "manutentori del verde capisquadra e responsabili": "عمال صيانة المساحات الخضراء ورؤساء فرق",
    "manutentore del verde vivaismo": "عامل صيانة المساحات الخضراء في المشاتل",
    "manutentore piante d interno": "عامل صيانة النباتات الداخلية",
    "manutentore verde": "عامل صيانة المساحات الخضراء",
    "manutentore giardiniere": "عامل صيانة بستاني",
    "manutentore verde giardiniere": "عامل صيانة المساحات الخضراء بستاني",
    "manutentore di giardini": "عامل صيانة حدائق",
    "manutentore del verde esperto": "عامل صيانة مساحات خضراء خبير",
    "manutentore giardino": "عامل صيانة حديقة",
    "manutenzione del verde": "صيانة المساحات الخضراء",
    "manutenzione verde": "صيانة المساحات الخضراء",
    "manutenzione e creazione del verde": "صيانة وإنشاء المساحات الخضراء",
    "manutenzione e creazione giardini": "صيانة وإنشاء حدائق",
    "manutenzione giardini e piante da frutta": "صيانة حدائق وأشجار مثمرة",
    "manutenzione piante da interni e giardini": "صيانة النباتات الداخلية والحدائق",
    "manutenzione del verde e lavori boschivi": "صيانة المساحات الخضراء وأعمال الغابات",
    "manutenzione verde pubblico": "صيانة المساحات الخضراء العمومية",
    "manutenzione del verde e giardini": "صيانة المساحات الخضراء والحدائق",
    "manutenzione verde e giardini": "صيانة المساحات الخضراء والحدائق",
    "messo a dimora": "موظف غرس النباتات",
    "messa a dimora": "موظفة غرس النباتات",
    "progettazione e realizzazione di terrazzi": "تصميم وإنجاز الشرفات",
    "progettazione realizzazione e manutenzione": "تصميم وإنجاز وصيانة الحدائق",
    "progettazione del verde": "تصميم المساحات الخضراء",
    "progettazione e realizzazione giardini": "تصميم وإنجاز الحدائق",
    "progettista del verde": "مصمم المساحات الخضراء",
    "progettista architetto paesaggista garden": "مصمم مهندس تنسيق الحدائق",
    "progettista": "مصمم",
    "progettista giardini": "مصمم حدائق",
    "progettista tecnico del verde": "مصمم فني للمساحات الخضراء",
    "progettista paesaggista": "مصمم تنسيق المناظر الطبيعية",
    "studio di progettazione": "مكتب تصميم",
    "collaboratore full time per progettazione": "متعاون بدوام كامل للتصميم",
    "renderista aiuto gestione garden": "مصمم تصورات مساعد لإدارة متجر الحدائق",
    "redattore praticante": "محرر متدرّب",
    "supporto al poject manager nella gestione": "دعم لمدير المشروع في التسيير",
    "gestione lavori e squadre": "تدبير الأشغال والفرق",
    "area commerciale": "المجال التجاري",
    "ufficio tecnico": "المكتب التقني",
    "segretaria": "موظفة إدارة",
    "segreteria": "موظف إدارة",
    "amministrazione": "موظف إداري",
    "contabilita cantiere": "محاسبة الورشات",
    "impiegato a back office pest control": "موظف مكاتب خلفية مكافحة الآفات",
    "impiegato tecnico pest control nord est italia": "موظف فني مكافحة آفات شمال شرق إيطاليا",
    "impiegato commerciale back office": "موظف تجاري مكتب خلفي",
    "impiegato amministrativo": "موظف إداري",
    "impiegati di cantiere": "موظفو الورشات",
    "impiegato tecnico": "موظف تقني",
    "figura professionale": "منصب مهني",
    "venditore": "بائع",
    "venditore specializzato": "بائع متخصص",
    "venditrice garden center": "بائعة مركز بيع منتجات الحدائق",
    "vendita vini e altri prodotti aziendali comunicazione": "بيع نبيذ ومنتجات أخرى مع التواصل",
    "vendita 2 negozi di fiori e piante e due": "بيع متجري زهور ونباتات",
    "vendite e allestimento": "مبيعات وتجهيز",
    "commerciale": "موظف تجاري",
    "agente vendite": "وكيل مبيعات",
    "commesso": "موظف مبيعات",
    "commessa": "موظفة مبيعات",
    "commessa a": "موظفة مبيعات",
    "commesso a": "موظف مبيعات",
    "commesso per garden": "موظف مبيعات متجر الحدائق",
    "commesso magazziniere": "موظف مبيعات وعامل مستودع",
    "commessa addetta al garden e reparto fioreria": "موظفة متجر الحدائق وقسم الزهور",
    "commessa addetta garden center": "موظفة مركز بيع الحدائق",
    "commessa nel garden realizzazione di creazioni": "موظفة متجر حدائق وصناعة تنسيقات",
    "commessa cassiera": "موظفة مبيعات وخزينة",
    "commessa addetta alla vendita": "موظفة مبيعات",
    "commessa fiorista": "موظفة مبيعات وبائعة زهور",
    "commessa garden": "موظفة متجر الحدائق",
    "fiorista commessa garden": "بائعة زهور متجر الحدائق",
    "commessa di negozio": "موظفة متجر",
    "commesso di negozio": "موظف متجر",
    "sales assistant": "مساعد مبيعات",
    "referente negozio e vivaio": "مسؤول متجر ومشتل",
    "referente store": "مسؤول المتجر",
    "responsabile punti vendita": "مسؤول نقاط البيع",
    "magazziniere": "عامل مستودع",
    "addetto magazzino": "موظف مستودع",
    "magazziniere giardiniere": "عامل مستودع بستاني",
    "autista patente c ragnista": "سائق بالرخصة C متخصص في التسلق",
    "autista patente c": "سائق بالرخصة C",
    "autista patente c manutenzione verde": "سائق بالرخصة C لصيانة المساحات الخضراء",
    "autista piattaforme aeree patente c": "سائق منصات مرتفعة بالرخصة C",
    "autista": "سائق",
    "autista giardiniere": "سائق بستاني",
    "trattorista": "سائق جرار",
    "trattorista manutentore del verde": "سائق جرار صيانة المساحات الخضراء",
    "trattorista autista": "سائق جرار",
    "trattorista agricolo": "سائق جرار فلاحي",
    "escavatorista": "سائق حفارة",
    "meccanico macchinari da giardinaggio": "ميكانيكي آلات الحدائق",
    "meccanico attrezzatura da giardinaggio": "ميكانيكي معدات الحدائق",
    "meccanico addetto noleggio": "ميكانيكي مسؤول الإيجارات",
    "meccanico": "ميكانيكي",
    "saldatore": "عامل لحام",
    "idraulico": "سباك",
    "elettricista": "كهربائي",
    "installatore verde stabilizzato": "مُركب العشب الصناعي",
    "installatore robot rasaerba": "مُركب جزّازات آلية",
    "installatore": "مُركب",
    "installatore a verde": "مُركب مساحات خضراء",
    "impiantista irrigazione": "مُركب أنظمة الري",
    "impianti irrigazione": "مُركب أنظمة الري",
    "impiantista": "مُركب أنظمة",
    "tecnico disinfestatore": "فني مكافحة الآفات",
    "tecnico disinfestazione e allontanamento": "فني مكافحة الآفات وإبعاد الحيوانات",
    "tecnico del verde": "فني المساحات الخضراء",
    "tecnico del verde junior": "فني مساحات خضراء مبتدئ",
    "tecnico aree verdi": "فني المساحات الخضراء",
    "tecnico manutenzione verde": "فني صيانة المساحات الخضراء",
    "tecnico di cantiere": "فني ورشة",
    "tecnico di cantiere per il verde": "فني ورشة للمساحات الخضراء",
    "tecnico di cantiere appalti pubblici e privati": "فني ورشة أشغال عمومية وخاصة",
    "tecnico di commessa arboricoltore agronomo": "فني مشروع مختص بالأشجار مهندس زراعي",
    "tecnico per impianti trattamento acque": "فني أنظمة معالجة المياه",
    "tecnico agrario": "فني زراعي",
    "tecnico agronomo": "فني مهندس زراعي",
    "tecnico commerciale": "فني تجاري",
    "tecnico": "فني",
    "tecnico specializzato": "فني متخصص",
    "tecnico specializzato in agricoltura urbana": "فني متخصص في الفلاحة الحضرية",
    "tecnico capo cantiere": "فني رئيس ورشة",
    "tecnico responsabile commessa": "فني مسؤول مشروع",
    "tecnico progettista giardini e terrazzi": "فني مصمم حدائق وشرفات",
    "tecnico progettista del verde architetto": "فني مصمم المساحات الخضراء مهندس",
    "tecnico commercionale": "فني تجاري",
    "tecnico edile": "فني البناء",
    "tecnico agricolo": "فني فلاحي",
    "tecnico dei giardini": "فني الحدائق",
    "perito agrario": "خبير فلاحي",
    "capo tecnico": "رئيس فني",
    "capotecnico": "رئيس فني",
    "agronomo": "مهندس زراعي",
    "agronomo a": "مهندس زراعي",
    "agronomo iscritto all albo": "مهندس زراعي مسجل في النقابة",
    "agronomo forestale": "مهندس زراعي غابات",
    "agronomo florovivaista": "مهندس زراعي متخصص في النباتات",
    "ricerca agronomo florovivaista": "بحث عن مهندس زراعي متخصص في النباتات",
    "agronomo paesaggista": "مهندس زراعي تنسيق المناظر الطبيعية",
    "perito agrario tecnico del verde": "خبير فلاحي فني المساحات الخضراء",
    "o perito agrario tecnico del verde agronomagrotecnico": "خبير فلاحي فني المساحات الخضراء مهندس زراعي",
    "arboricoltore": "مختص في العناية بالأشجار",
    "arboricoltore agronomoc": "مختص بالأشجار مهندس زراعي",
    "arboricoltore certificato": "مختص معتمد في العناية بالأشجار",
    "arboricoltura": "أعمال العناية بالأشجار",
    "arboricultore": "مختص في العناية بالأشجار",
    "potatore piante ornamentali": "عامل تقليم نباتات الزينة",
    "potatore in quota": "عامل تقليم على علو",
    "potatore": "عامل تقليم الأشجار",
    "potatura alberi": "تقليم الأشجار",
    "potatura": "تقليم الأشجار",
    "espansione a potatura": "تقليم الأشجار",
    "climber": "متخصص في العمل المرتفع بالأشجار",
    "tree climber": "متخصص في العمل المرتفع بالأشجار",
    "treeclimber": "متخصص في العمل المرتفع بالأشجار",
    "treeclimber giardiniere": "متخصص في العمل المرتفع بالأشجار بستاني",
    "tree climbing": "متخصص في العمل المرتفع بالأشجار",
    "climber giardiniere": "متخصص في العمل المرتفع بالأشجار بستاني",
    "cercasi giovane climber": "نبحث عن شاب متخصص في التسلق",
    "greenkeeper": "مشرف الأراضي العشبية",
    "greenkeeper stagionale": "مشرف أراضي عشبية موسمي",
    "greenkeeper agronomo": "مشرف أراضٍ عشبية مهندس زراعي",
    "manutenzione del prato": "صيانة العشب",
    "mammoletta del verde": "عامل المساحات الخضراء",
    "fiorista": "بائع زهور",
    "fiorista con esperienza": "بائع زهور بخبرة",
    "fiorista con esperienza vivaista": "بائع زهور بخبرة في المشاتل",
    "fiorista qualificato": "بائع زهور مؤهل",
    "fiorista esperta o": "بائعة زهور بخبرة",
    "fiorista diplomata con esperienza": "بائعة زهور بشهادة وخبرة",
    "fiorista responsabile negozio": "بائع زهور مسؤول المتجر",
    "fiorista addetto alle vendite": "بائع زهور موظف مبيعات",
    "fiorista addetto a alla vendita e composizioni": "بائع زهور للبيع والتنسيقات",
    "fiorista e allestitore": "بائع زهور ومجهّز",
    "fiorista e decor": "بائع زهور ومزين",
    "fiorista florovivaista garden": "بائع زهور متخصص نباتات متجر الحدائق",
    "fiorista per negozio a milano": "بائع زهور لمتجر في ميلانو",
    "fiorista o vivaista": "بائع زهور أو عامل مشاتل",
    "fiorista junion apprendista": "بائعة زهور مبتدئة متدربة",
    "cerchiamo fiorista junion apprendista": "نبحث عن بائعة زهور مبتدئة متدربة",
    "assistente fiorista": "مساعد بائع زهور",
    "aiuto fiorista": "مساعد بائع زهور",
    "fioraio": "بائع زهور",
    "fioraia": "بائعة زهور",
    "fioreria": "قسم الزهور",
    "aiuto fiorista e giardiere": "مساعد بائع زهور وبستاني",
    "floral designer": "مصمم زهور",
    "flower designer": "مصمم زهور",
    "flower e garden design": "تصميم الزهور والحدائق",
    "fiorista floreria": "بائع زهور",
    "vivaista": "عامل في المشاتل النباتية",
    "vivaista fiorista": "عامل مشاتل وبائع زهور",
    "vivaista con esperienza o minimo interesse": "عامل مشاتل بخبرة أو برغبة أولية",
    "vivaista e giardiniere anche primo impiego": "عامل مشاتل وبستاني لبداية العمل",
    "vivaista giardiniere": "عامل مشاتل وبستاني",
    "operatore vivaista": "عامل مشاتل نباتات",
    "orto vivaista": "عامل مشاتل نباتية",
    "vivaismo": "العمل في المشاتل النباتية",
    "vivaio": "عامل مشتل نباتات",
    "personale serra vivaio": "موظفو الصوبات والمشاتل",
    "garden center": "مركز بيع منتجات الحدائق",
    "production manager": "مدير إنتاج",
    "pco pest control operator": "فني مكافحة الآفات",
    "allestitore trasportatore": "مجهّز وناقل",
    "tecnico vivaista": "فني المشاتل النباتية",
    "invasatrice": "موظفة زرع النباتات في الأواني",
    "invasatore": "موظف زرع النباتات في الأواني",
    "florovivaista": "متخصص في زراعة النباتات",
    "florovivaista garden": "متخصص نباتات في متجر الحدائق",
    "florovivaista e manutentore di giardino storico": "متخصص نباتات وعامل صيانة حديقة تاريخية",
    "florovivaista giardiniere": "متخصص في زراعة النباتات وبستاني",
    "operaio florovivaio": "عامل في النباتات",
    "giardino fiorito": "مسؤول منازل مزينة",
    "ortolano": "مزارع خضروات",
    "ortolano esperto": "مزارع خضروات خبير",
    "ortolano giardiniere": "مزارع خضروات بستاني",
    "ortolano agricolo": "مزارع خضروات فلاحي",
    "ortista giardiniere educatore ambientale": "بستاني ومربّي بيئي",
    "orticoltore": "مزارع خضروات",
    "giovane orticoltore o aspirante tale": "مزارع خضروات شاب أو مبتدئ",
    "Agricoltore": "مزارع / فلاح",
    "orticoltura": "زراعة الخضروات",
    "agricoltura": "الفلاحة",
    "agricoltura sociale": "الفلاحة الاجتماعية",
    "operatore di orto sociale": "عامل حديقة اجتماعية",
    "orto sociale": "عامل الحديقة الاجتماعية",
    "orto operaio orto": "عامل الحديقة النباتية",
    "gestore di orto e frutteto": "مدير حديقة نباتية وبستان",
    "agricoltore": "مزارع / فلاح",
    "viticultore": "عامل زراعة الكروم",
    "vendemmia 2022 e aiuto viticoltore vinificatore": "عمل موسمي وعامل كروم وصاحب معصرة نبيذ",
    "vignaiolo": "مزارع الكروم",
    "tutor per progetto di agricoltura sociale": "مؤطر مشروع الفلاحة الاجتماعية",
    "assistente alla coltivazione": "مساعد في الزراعة",
    "personale per la coltivazione": "موظفون للزراعة",
    "gestori stalla caprina e caseificio": "مديرو إسطبل الماعز ومصنع الأجبان",
    "esigenza nella propria azienda di capre": "عمل في مزرعة ماعز خاصة",
    "esperienza nella propria azienda di capre": "خبرة في مزرعة ماعز خاصة",
    "boscaiolo": "حطّاب",
    "impresa boschiva giardiniere": "شركة غابات بستاني",
    "edile stradale": "عامل أبنية وطرق",
    "edile": "عامل بناء",
    "muratore": "بَنّاء",
    "carpentiere": "نجّار بناء",
    "impresa edile": "شركة بناء",
    "operai edili": "عمال بناء",
    "attrezzista di scena": "فني تجهيز المسارح",
    "promoter utensili potatura": "مروّج أدوات التقليم",
    "promoter": "مروّج",
    "dimostratore di macchine professionali per": "مروّج آلات مهنية",
    "dimostratore utensili potatura centro sud": "مروّج أدوات تقليم لمنطقة الجنوب",
    "specialista macchine e attrezzature agricole": "متخصص آلات ومعدات فلاحية",
    "specialista meccanizzazione agricola": "متخصص في المكننة الفلاحية",
    "specialista di negozio garden": "متخصص متجر الحدائق",
    "specialista giardini": "متخصص في الحدائق",
    "specialista del verde": "متخصص المساحات الخضراء",
    "specialista potatura": "متخصص في التقليم",
    "specialista giardiniere": "متخصص بستاني",
    "specialista in potatura": "متخصص في التقليم",
    "specialista vendite": "متخصص مبيعات",
    "personale per la manutenzione del verde": "موظفون لصيانة المساحات الخضراء",
    "personale esperto in manutenzione e realizzazione": "موظفون خبراء في الصيانة والإنجاز",
    "persona seria e con voglia di lavorare": "شخص جاد وراغب في العمل",
    "ragazza o con molta voglia di lavorare imparare": "فتاة شابة أو شخص راغب جداً في العمل والتعلم",
    "ragazzo o ragazza con voglia di lavorare": "شاب أو فتاة راغب في العمل",
    "volontari per realizzazione giardino al castello": "متطوعون لإنجاز حديقة القلعة",
    "lavoro in vivaio e agricoltura biologica": "عمل في المشاتل والفلاحة البيولوجية",
    "lavoro in sede": "عمل في مقر الشركة",
    "lavori di giardinaggio": "أعمال الحدائق",
    "lavori di giardinaggi imbiancature": "أعمال حدائق ودهن",
    "lavori in quota": "أعمال على علو",
    "formazione per lavori in quota su funi e": "تكوين للعمل على علو بالحبال",
    "capacita di usare i principali attrezzi decespugliatore": "القدرة على استعمال أدوات القص الرئيسية",
    "esperienza mininima nel giardinaggio": "خبرة بسيطة في أعمال الحدائق",
    "esperienza di un anno circa": "خبرة سنة تقريباً",
    "esperienza nel giardinaggio": "خبرة في أعمال الحدائق",
    "esperienza nel settore": "خبرة في المجال",
    "esperienza nella manutenzione del verde": "خبرة في صيانة المساحات الخضراء",
    "esperienza nella potatura": "خبرة في التقليم",
    "con esperienza nel settore del verde": "بخبرة في مجال المساحات الخضراء",
    "con esperienza nelle potature": "بخبرة في التقليم",
    "giovane con esperienza nel verde": "شاب بخبرة في المساحات الخضراء",
    "giovane giardiniere": "بستاني شاب",
    "giovane e dinamico": "شاب وحيوي",
    "autista c": "سائق بالرخصة C",
    "patente c": "بالرخصة C",
    "con patente c": "بالرخصة C",
    "patente b": "بالرخصة B",
    "con patente b": "بالرخصة B",
    "personale con patente c": "موظفون بالرخصة C",
    "patentino ple": "برخصة PLE",
    "con patentino ple": "برخصة PLE",
    "ple": "رخصة PLE",
    "p i": "العمل الحر",
    "p.iva": "العمل الحر",
    "partita iva": "نظام العمل الحر",
    "con partita iva": "بنظام العمل الحر",
    "con p iva": "بنظام العمل الحر",
    "a partita iva": "بنظام العمل الحر",
    "a piva": "بنظام العمل الحر",
    "piva": "العمل الحر",
    "cercasi giardiniere": "نبحث عن بستاني",
    "cercasi giardiniere base con qualifica": "نبحث عن بستاني مبتدئ مؤهل",
    "cercasi ortoterapista comunita": "نبحث عن معالج بالبستنة للمجتمع",
    "cercasi operatore agricolo": "نبحث عن عامل فلاحي",
    "cerchiamo profilo giardiniere gia formato": "نبحث عن بستاني مكوّن",
    "cerco operaio giardiniere e apprendista": "نبحث عن عامل بستاني ومتدرب",
    "ricerca operaio giardiniere": "بحث عن عامل بستاني",
    "ricerca giardiniere": "بحث عن بستاني",
    "ricerca operai per giardinaggio": "بحث عن عمال للحدائق",
    "ricerca manutentore del verde": "بحث عن عامل صيانة المساحات الخضراء",
    "ricerca personale": "بحث عن موظفين",
    "ricercasi addetto giardiniere": "بحث عن موظف بستاني",
    "ricercasi giardiniere": "بحث عن بستاني",
    "ricerca addestrato giardiniere": "بحث عن بستاني متكوّن",
    "offerta lavoro giardiniere": "عرض عمل بستاني",
    "offerta lavoro manutentore del verde": "عرض عمل عامل صيانة المساحات الخضراء",
    "offertas di lavoro giardiniere": "عرض عمل بستاني",
    "assunzione giardiniere": "توظيف بستاني",
    "assunzione operai": "توظيف عمال",
    "assunzione manutentore verde": "توظيف عامل صيانة المساحات الخضراء",
    "assunzione operai giardinieri": "توظيف عمال بستانيين",
    "assunzione florovivaisti": "توظيف متخصصي نباتات",
    "ricerchiamo giardiniere": "نبحث عن بستاني",
    "ricerchiamo operai": "نبحث عن عمال",
    "ricerchiamo manutentore del verde": "نبحث عن عامل صيانة المساحات الخضراء",
    "ricerchiamo giardinieri": "نبحث عن بستانيين",
    "cercasi giardinieri": "نبحث عن بستانيين",
    "cercasi manutentore del verde": "نبحث عن عامل صيانة المساحات الخضراء",
    "cerchiamo giardiniere": "نبحث عن بستاني",
    "cerchiamo manutentore": "نبحث عن عامل صيانة",
    "cerchiamo personale": "نبحث عن موظفين",
    "siamo alla ricerca di giardiniere": "نبحث عن بستاني",
    "ricerca di giardiniere": "بحث عن بستاني",
    "ricerca di un giardiniere": "بحث عن بستاني",
    "ricerca di personale": "بحث عن موظفين",
    "ricerca di un manutentore del verde": "بحث عن عامل صيانة المساحات الخضراء",
    "ricerca manutenzione del verde": "بحث عن صيانة المساحات الخضراء",
    "ricerca collaboratori": "بحث عن متعاونين",
    "ricerca volontari": "بحث عن متطوعين",
    "siamo alla ricerca di": "نبحث عن",
    "la piramide lavoro soc cooperativa sociale": "تعاونية نبحث عن عمال",
    "siamo una cooperativa sociale": "نحن تعاونية اجتماعية",
    "siamo una azienda agricola": "نحن شركة فلاحية",
    "siamo azienda agricola": "نحن شركة فلاحية",
    "azienda agricola cerca": "شركة فلاحية تبحث عن",
    "aziende agricole": "شركات فلاحية",
    "azienda agricola": "شركة فلاحية",
    "societa agricola cerca": "شركة فلاحية تبحث عن",
    "cooperativa sociale cerca": "تعاونية اجتماعية تبحث عن",
    "cooperativa cerca": "تعاونية تبحث عن",
    "agriturismo cerca": "فندق ريفي يبحث عن",
    "terreno per garden": "أرض لمتجر الحدائق",
    "produzione di prato pronto a rotoli e manutenzioni": "إنتاج العشب الجاهز وخدمات الصيانة",
    "produzione provato": "إنتاج العشب الجاهز",
    "e commerce settore del verde": "تجارة إلكترونية في قطاع المساحات الخضراء",
    "pulizia e manutenzione del verde": "تنظيف وصيانة المساحات الخضراء",
    "pulizia verde": "تنظيف المساحات الخضراء",
    "addetto alle pulizie": "موظف تنظيف",
    "addetto alle pulizie verde": "موظف تنظيف المساحات الخضراء",
    "giardinaggio in genere": "أعمال حدائق عامة",
    "attivita di giardinaggio": "أعمال الحدائق",
    "attività di giardinaggio": "أعمال الحدائق",
    "lavori di giardinaggio e manutenzione": "أعمال حدائق وصيانة",
    "gestione del verde": "تدبير المساحات الخضراء",
    "gestione parco": "تدبير الحديقة",
    "gestione verde": "تدبير المساحات الخضراء",
    "tutela del verde": "حماية المساحات الخضراء",
    "campo di giardinaggio": "عامل حدائق",
    "otticoltura": "زراعة الخضروات",
    "giardinetico": "بستاني",
    "giardinaggio": "أعمال الحدائق",
    "giardinaggio e manutenzione": "أعمال حدائق وصيانة",
    "giardini": "بستاني",
    "giardini ornamentali": "الحدائق الزينة",
    "giardinaggio ornamentale": "أعمال حدائق زينة",
    "giardino storico": "حديقة تاريخية",
    "giardino pensile": "حديقة معلقة",
    "giardiniere per giardino": "بستاني لحديقة",
    "giardiniere p.iva": "بستاني بنظام العمل الحر",
    "giardiniere vere": "بستاني",
    "jardinier": "بستاني",
    "gardener giardiniere": "بستاني",
    "giardinierere a": "بستاني",
    "giardinere": "بستاني",
    "giardinieri": "بستانيون / عمال الحدائق",
    "giardinieri con esperienza": "بستانيون بخبرة",
    "giardinieri con esperienza e aiuto giardinieri": "بستانيون بخبرة ومساعدو بستانيين",
    "giardinieri specializzati": "بستانيون متخصصون",
    "giardinieri manutentori aree verdi": "بستانيون لصيانة المساحات الخضراء",
    "giardiniera": "عاملة حدائق",
    "giardinero": "بستاني",
    "giardinerie": "بستاني",
    "duplice impiego giardiniere": "بستاني لعمل مزدوج",
    "squadra giardinieri": "فريق بستانيين",
    "squadra manutenzione verde": "فريق صيانة المساحات الخضراء",
    "squadra manutenzioni giardini": "فريق صيانة حدائق",
    "squadre di giardinieri": "فرق بستانيين",
    "capo vivaio": "رئيس المشتل النباتي",
    "altro": "غير ذلك",
    "altro ruolo": "دور آخر",
    "altro settore": "قطاع آخر",
    "altro incarico": "وظيفة أخرى",
}

# Small fallback glossary used to compose a readable Arabic rendering for any
# future/new title not in AR_TITLES (single words + short phrases, longest
# match wins). Kept deliberately small: unknown words stay in Latin rather
# than producing a bad literal translation.
AR_GLOSSARY = {
    "giardiniere": "بستاني",
    "giardinieri": "بستانيون",
    "giardiniera": "عاملة حدائق",
    "operaio": "عامل",
    "operaia": "عاملة",
    "operai": "عمال",
    "addetto": "موظف",
    "addetta": "موظفة",
    "aiuto": "مساعد",
    "apprendista": "متدرب",
    "stagista": "متدرب",
    "tirocinante": "متدرب",
    "collaboratore": "متعاون",
    "collaboratrice": "متعاونة",
    "assistente": "مساعد",
    "tecnico": "فني",
    "agronomo": "مهندس زراعي",
    "manutentore": "عامل صيانة",
    "manutenzione": "صيانة",
    "manutentori": "عمال صيانة",
    "fiorista": "بائع زهور",
    "vivaista": "عامل مشاتل",
    "florovivaista": "متخصص في زراعة النباتات",
    "arboricoltore": "مختص بالأشجار",
    "paesaggista": "مهندس تنسيق",
    "caposquadra": "رئيس فريق",
    "responsabile": "مسؤول",
    "titolare": "صاحب العمل",
    "venditore": "بائع",
    "venditrice": "بائعة",
    "commesso": "موظف مبيعات",
    "commessa": "موظفة مبيعات",
    "magazziniere": "عامل مستودع",
    "custode": "حارس",
    "autista": "سائق",
    "trattorista": "سائق جرار",
    "boscaiolo": "حطّاب",
    "agricoltore": "مزارع",
    "ortolano": "مزارع خضروات",
    "orticoltore": "مزارع خضروات",
    "impiegato": "موظف",
    "impiegata": "موظفة",
    "consulente": "مستشار",
    "artigiano": "حرفي",
    "meccanico": "ميكانيكي",
    "architetto": "مهندس معماري",
    "progettista": "مصمم",
    "potatore": "عامل تقليم",
    "potatura": "تقليم الأشجار",
    "agente": "وكيل",
    "promoter": "مروّج",
    "specialista": "متخصص",
    "operatore": "عامل",
    "operatrice": "عاملة",
    "gardener": "بستاني",
    "climber": "متخصص في العمل المرتفع",
    "treeclimber": "متخصص في العمل المرتفع",
    "esposo": "متخصص",
    "apprendistato": "تكوين مهني",
    "primo impiego": "أول عمل",
    "senza esperienza": "بدون خبرة",
    "con esperienza": "بخبرة",
    "esperienza": "خبرة",
    "qualificato": "مؤهل",
    "specializzato": "متخصص",
    "professionista": "محترف",
    "professionale": "محترف",
    "esperto": "خبير",
    "base": "مبتدئ",
    "comune": "عادي",
    "generico": "عام",
    "stagionale": "موسمي",
    "autonomo": "مستقل",
    "part time": "بدوام جزئي",
    "full time": "بدوام كامل",
    "del verde": "المساحات الخضراء",
    "delle aree verdi": "المساحات الخضراء",
    "verde": "المساحات الخضراء",
    "aree verdi": "المساحات الخضراء",
    "giardino": "حديقة",
    "giardini": "الحدائق",
    "giardinaggio": "أعمال الحدائق",
    "vivaio": "المشتل النباتي",
    "vivaismo": "المشاتل النباتية",
    "serra": "صوبة",
    "agricolo": "فلاحي",
    "agricola": "فلاحية",
    "agricoltura": "الفلاحة",
    "forestale": "غابات",
    "biologica": "بيولوجية",
    "manutenzione del verde": "صيانة المساحات الخضراء",
    "manutentore del verde": "عامل صيانة المساحات الخضراء",
    "cantiere": "ورشة",
    "partita iva": "العمل الحر",
    "p iva": "العمل الحر",
    "patente c": "الرخصة C",
    "con patente c": "بالرخصة C",
}

# Italian connectives dropped while composing the fallback translation.
AR_STOP = set(
    ("il", "lo", "la", "i", "gli", "le", "un", "uno", "una", "del", "della",
     "delle", "dei", "dello", "dal", "dalla", "dalle", "dai", "al", "alla",
     "alle", "ai", "di", "da", "in", "su", "per", "con", "e", "ed", "o",
     "che", "non", "anche", "a", "nel", "nella", "nelle", "all", "agli", "degli")
)


def ar_title(raw):
    """Arabic translation for an Italian job title — local, deterministic,
    hand-authored. Returns "" when no confident Arabic rendering exists."""
    t = " ".join(str(raw).split()).lower()
    if not t:
        return ""
    if t in AR_TITLES:
        return AR_TITLES[t]

    # Keep legal/number references (e.g. "dlgs 154 2016", "patente c b") verbatim.
    words = t.split(" ")
    refs, rest = [], []
    for w in words:
        if re.search(r"[0-9]", w):
            refs.append(w)
        else:
            rest.append(w)

    keys = sorted(AR_GLOSSARY, key=lambda k: (len(k.split()), len(k)), reverse=True)
    gloss = {k: AR_GLOSSARY[k] for k in keys}

    out, i = [], 0
    while i < len(rest):
        seg = rest[i]
        matched = None
        for key in keys:
            n = len(key.split())
            if n <= len(rest) - i and " ".join(rest[i:i + n]) == key:
                matched = (gloss[key], n)
                break
        if matched:
            out.append(matched[0])
            i += matched[1]
        elif seg in AR_STOP:
            i += 1
        else:
            out.append(seg)
            i += 1

    if not out or not re.search(r"[\u0600-\u06FF]", " ".join(out)):
        return ""
    arabic = " ".join(out).strip()
    if refs:
        refs_joined = " ".join(refs)
        refs_joined = re.sub(r"(\d+) (\d+)", r"\1/\2", refs_joined)
        arabic += " " + refs_joined
    return arabic


def main():
    if not os.path.exists(CSV_PATH):
        print("ERROR: %s not found" % CSV_PATH, file=sys.stderr)
        sys.exit(1)

    with io.open(CSV_PATH, "r", encoding="utf-8-sig", newline="") as fh:
        reader = csv.DictReader(fh)
        if reader.fieldnames is None or [c.strip() for c in reader.fieldnames] != COLUMNS:
            print(
                "ERROR: bad header, expected exactly: %s" % ", ".join(COLUMNS),
                file=sys.stderr,
            )
            sys.exit(1)
        rows = [dict(r) for r in reader]

    records = []
    seen = set()
    dupes = 0
    titles_from_csv = 0
    titles_from_source = 0
    arabic_covered = 0
    for i, r in enumerate(rows):
        source = (r.get("Source") or "").strip()
        if not source:
            print("WARN: row %d has no Source, skipped" % (i + 2))
            continue
        if source in seen:
            dupes += 1
            continue
        seen.add(source)
        rec = {}
        for key, col in zip(KEYS, COLUMNS):
            val = (r.get(col) or "").strip()
            rec[key] = val if val else "-"

        # Title: keep Posizione verbatim when present, otherwise derive it from
        # the Source slug. Never overwrite an existing Posizione.
        posizione = (r.get("Posizione") or "").strip()
        if posizione:
            titles_from_csv += 1
        else:
            derived = slug_title(source)
            if derived:
                rec["t"] = derived
                titles_from_source += 1

        # Arabic helper translation (a) — local, deterministic, never part of
        # the Italian title. Empty/nonexistent AR renderings become "-".
        if rec.get("t") and rec["t"] != "-":
            arabic = ar_title(rec["t"])
        else:
            arabic = ""
        rec["a"] = arabic if arabic else "-"
        if arabic:
            arabic_covered += 1

        records.append(rec)

    payload = json.dumps(records, ensure_ascii=False, separators=(",", ":"))

    out = (
        "/* Generated by tools/generate-offers-italia-data.py from italia.csv — DO NOT EDIT BY HAND.\n"
        "   Re-run `python tools/generate-offers-italia-data.py` after updating italia.csv.\n"
        "   Record fields: t=Posizione e=Ragione sociale m=Email cm=Comune pv=Provincia u=Source url,\n"
        "   a=Arabic helper translation of the job title (local, hand-authored; \"-\" when none). */\n"
        "window.OFFERS_IT_DATA = %s;\n" % payload
    )

    with io.open(OUT_PATH, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(out)

    print("Offers loaded .....: %d rows" % len(rows))
    print("Duplicates dropped : %d" % dupes)
    print("Records emitted ...: %d" % len(records))
    print("Titles from Posizione: %d" % titles_from_csv)
    print("Titles from Source slug: %d" % titles_from_source)
    print("Arabic titles ......: %d" % arabic_covered)
    print("Output ............: %s" % OUT_PATH)


if __name__ == "__main__":
    main()