#!/usr/bin/env python3
"""
Generate js/offers-italia-data.js from italia.csv (MonzaFlora offers).

Pure local, NO network access. Run:  python tools/generate-offers-italia-data.py

CSV columns (verbatim header):
    Posizione, Ragione sociale, Email, Comune, Provincia, Source

Each generated record keeps the Italian values untouched:
    t  = Posizione (job position)
    e  = Ragione sociale (employer name)
    m  = Email
    cm = Comune
    pv = Provincia
    u  = Source URL (the original job offer link)
Missing CSV values stay as-is ("-"), the JS layer renders them as مكتقدرش نعرفو.
Exception: when Posizione (t) is empty, the title is derived from the Source
slug (fallback, see slug_title) — an existing Posizione is never replaced.
"""

import csv
import io
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CSV_PATH = os.path.join(ROOT, "italia.csv")
OUT_PATH = os.path.join(ROOT, "js", "offers-italia-data.js")

COLUMNS = ["Posizione", "Ragione sociale", "Email", "Comune", "Provincia", "Source"]
KEYS = ["t", "e", "m", "cm", "pv", "u"]


def slug_title(url):
    """Readable Italian title derived from the Source slug — local and deterministic.

    Only used as a FALLBACK when Posizione is empty; an existing Posizione is
    never replaced. Steps: strip fragment/query -> last part after /offerte/
    -> '-' becomes spaces -> drop a trailing slug index ("-6", "-61") only when
    the segment before it is NOT numeric (so "...-dlgs-154-2016" is preserved)
    -> sentence case. No network, no scraping.
    """
    clean = url.split("#", 1)[0].split("?", 1)[0]
    tail = clean.split("/offerte/")[-1] if "/offerte/" in clean else clean.rstrip("/").split("/")[-1]
    parts = [p for p in tail.split("-") if p]
    if len(parts) >= 2 and parts[-1].isdigit() and not parts[-2].isdigit():
        parts.pop()
    title = " ".join(parts).strip()
    if title:
        title = title[0].upper() + title[1:]
    return title


def main():
    if not os.path.exists(CSV_PATH):
        print("ERROR: %s not found" % CSV_PATH, file=sys.stderr)
        sys.exit(1)

    with io.open(CSV_PATH, "r", encoding="utf-8-sig", newline="") as fh:
        reader = csv.DictReader(fh)
        if reader.fieldnames is None or [c.strip() for c in reader.fieldnames] != COLUMNS:
            print(
                "ERROR: bad header, expected exactly: %s" % ", ".join(COLUMNS),
                file=sys.stderr,
            )
            sys.exit(1)
        rows = [dict(r) for r in reader]

    records = []
    seen = set()
    dupes = 0
    titles_from_csv = 0
    titles_from_source = 0
    for i, r in enumerate(rows):
        source = (r.get("Source") or "").strip()
        if not source:
            print("WARN: row %d has no Source, skipped" % (i + 2))
            continue
        if source in seen:
            dupes += 1
            continue
        seen.add(source)
        rec = {}
        for key, col in zip(KEYS, COLUMNS):
            val = (r.get(col) or "").strip()
            rec[key] = val if val else "-"

        # Title: keep Posizione verbatim when present, otherwise derive it from
        # the Source slug. Never overwrite an existing Posizione.
        posizione = (r.get("Posizione") or "").strip()
        if posizione:
            titles_from_csv += 1
        else:
            derived = slug_title(source)
            if derived:
                rec["t"] = derived
                titles_from_source += 1

        records.append(rec)

    payload = json.dumps(records, ensure_ascii=False, separators=(",", ":"))

    out = (
        "/* Generated by tools/generate-offers-italia-data.py from italia.csv — DO NOT EDIT BY HAND.\n"
        "   Re-run `python tools/generate-offers-italia-data.py` after updating italia.csv.\n"
        "   Record fields: t=Posizione e=Ragione sociale m=Email cm=Comune pv=Provincia u=Source (source URL). */\n"
        "window.OFFERS_IT_DATA = %s;\n" % payload
    )

    with io.open(OUT_PATH, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(out)

    print("Offers loaded .....: %d rows" % len(rows))
    print("Duplicates dropped : %d" % dupes)
    print("Records emitted ...: %d" % len(records))
    print("Titles from Posizione: %d" % titles_from_csv)
    print("Titles from Source slug: %d" % titles_from_source)
    print("Output ............: %s" % OUT_PATH)


if __name__ == "__main__":
    main()